services:
  afl:
    container_name: zlib-afl-test-baseline
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - zlib-afl-out:/workspace/out
volumes:
  zlib-afl-out:
