FROM aflplusplus/aflplusplus:stable

RUN apt-get update && apt-get install -y \
    make cmake pkg-config wget curl git tmux

WORKDIR /src

RUN git clone https://github.com/madler/zlib.git && \
    cd zlib && \
    git checkout v1.3

WORKDIR /src/zlib
RUN CC=afl-clang-lto ./configure --static && \
    make -j$(nproc)

COPY harness.c .

RUN afl-clang-lto -O3 harness.c -o target_normal \
    -I/src/zlib \
    /src/zlib/libz.a \
    /usr/local/lib/afl/libAFLDriver.a \
    -ldl -lpthread -lm

RUN mkdir -p /workspace
RUN cp target_normal /workspace/target_normal

RUN mkdir -p /workspace/in
RUN echo "init_seed" > /workspace/in/seed

WORKDIR /workspace
COPY run_all.sh /workspace/
RUN chmod +x run_all.sh
