FROM my-aflplusplus:latest

RUN apt-get update && apt-get install -y \
    make autoconf libtool pkg-config wget curl git \
    liblzma-dev libz-dev libssl-dev libicu-dev \
    python3-dev python3-pip

WORKDIR /src

RUN git clone --depth 1 https://gitlab.gnome.org/GNOME/libxml2.git

RUN mkdir -p /deps

# ================= build libxml2 with AFL instrumentation (Normal) =================
WORKDIR /src/libxml2
RUN ./autogen.sh

RUN CC=afl-clang-lto CXX=afl-clang-lto++ ./configure \
    --without-debug \
    --without-ftp \
    --without-http \
    --without-python \
    --enable-static \
    --disable-shared \
    --with-icu

RUN make -j$(nproc)
RUN rm cfg_edges.txt

COPY harness.c .

RUN afl-clang-lto -O3 harness.c -o target_normal \
    -I/src/libxml2/include \
    /src/libxml2/.libs/libxml2.a \
    -lz -lm -lpthread -licuuc -licudata -lpthread \
    /usr/local/lib/afl/libAFLDriver.a
RUN cp target_normal /workspace/target_normal
RUN cp cfg_edges.txt /workspace/cfg_edges.txt

RUN mkdir -p /workspace/in
RUN find /src/libxml2/test -name "*.xml" -exec cp {} /workspace/in/ \;

WORKDIR /workspace
COPY *.sh /workspace/