services:
  afl:
    container_name: c-ares-afl-test-baseline
    build: .
    command: /bin/bash -c "./run_all.sh && sleep infinity"
    working_dir: /workspace
    volumes:
      - c-ares-afl-out:/workspace/out
volumes:
  c-ares-afl-out:
