FROM aflplusplus/aflplusplus:stable

RUN apt-get update && apt-get install -y \
    make cmake pkg-config wget curl git tmux unzip

WORKDIR /src

RUN git clone https://github.com/c-ares/c-ares.git && \
    cd c-ares && \
    git checkout v1.34.6

WORKDIR /src/c-ares
RUN mkdir -p build && cd build && \
    CC=afl-clang-lto CXX=afl-clang-lto++ cmake \
    -DCARES_SHARED=OFF -DCARES_STATIC=ON -DCARES_BUILD_TESTS=OFF -DCARES_BUILD_TOOLS=OFF .. && \
    make -j$(nproc)

COPY harness.c .

RUN afl-clang-lto -O3 harness.c -o target_normal \
    -I/src/c-ares/include -I/src/c-ares/build \
    /src/c-ares/build/lib/libcares.a \
    /usr/local/lib/afl/libAFLDriver.a \
    -ldl -lpthread -lm

RUN mkdir -p /workspace
RUN cp target_normal /workspace/target_normal

RUN mkdir -p /workspace/in
RUN echo "example.com" > /workspace/in/seed

WORKDIR /workspace
COPY run_all.sh /workspace/
RUN chmod +x run_all.sh
