services:
  afl:
    container_name: libxml2-afl-test
    build: .
    command: sleep infinity
    working_dir: /workspace
    ports:
      - "8060:8050"
    volumes:
      - ./artifacts:/workspace/artifacts