services:
  afl:
    container_name: libpng-afl-test-baseline
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - libpng-afl-out:/workspace/out
volumes:
  libpng-afl-out:
