FROM aflplusplus/aflplusplus:stable

RUN apt-get update && apt-get install -y \
    make autoconf libtool pkg-config wget curl git unzip tmux \
    libbz2-dev liblzo2-dev liblzma-dev liblz4-dev libz-dev \
    libssl-dev libacl1-dev libattr1-dev sharutils libxml2-dev

WORKDIR /src

RUN git clone https://github.com/libarchive/libarchive.git && \
    cd libarchive && \
    git checkout v3.7.1

WORKDIR /src/libarchive
RUN mkdir -p build && cd build && \
    CC=afl-clang-lto cmake -DDONT_FAIL_ON_CRC_ERROR=ON \
    -DENABLE_WERROR=OFF \
    -DENABLE_XATTR=OFF \
    -DENABLE_ACL=ON \
    -DENABLE_SHARED=OFF \
    -DENABLE_CPIO=OFF .. && \
    make -j$(nproc)
RUN mkdir -p /deps
RUN cp build/libarchive/libarchive.a /deps/libarchive.a

COPY harness.cc .

RUN afl-clang-lto++ -O3 harness.cc -o target_normal \
    -I/src/libarchive/libarchive \
    -I/src/libarchive/build/libarchive \
    /deps/libarchive.a \
    -Wl,-Bstatic -llzo2 -llzma -llz4 -lbz2 -lz -lzstd \
    -Wl,-Bdynamic -lcrypto -lacl -lm -ldl -lpthread -lxml2 \
    /usr/local/lib/afl/libAFLDriver.a

RUN mkdir -p /workspace
RUN cp target_normal /workspace/target_normal

RUN mkdir -p /workspace/in
# Seed with a small tar entry
RUN echo "test" > test.txt && tar -cvf /workspace/in/seed.tar test.txt

WORKDIR /workspace
COPY run_all.sh /workspace/
RUN chmod +x run_all.sh
