services:
  whisper:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: vul-neuron
    working_dir: /workspace

    volumes:
      - ./:/workspace
      - ./hf-cache:/root/.cache/huggingface

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: sleep infinity