services:
  afl-origin-1:
    container_name: libming-4.7_swftophp_2017-11728-afl-origin-1
    build:
      context: .
      dockerfile: base.dockerfile
    image: libming-4.7-swftophp-201711728-base:latest
    command: bash -c "bash script.sh && sleep infinity"
    working_dir: /workspace
    cpuset: "5"
    volumes:
      - libming-4.7_swftophp_2017-11728-afl-origin-1:/workspace/out

  afl-origin-2:
    container_name: libming-4.7_swftophp_2017-11728-afl-origin-2
    image: libming-4.7-swftophp-201711728-base:latest
    command: bash -c "bash script.sh && sleep infinity"
    working_dir: /workspace
    cpuset: "6"
    volumes:
      - libming-4.7_swftophp_2017-11728-afl-origin-2:/workspace/out

  afl-origin-3:
    container_name: libming-4.7_swftophp_2017-11728-afl-origin-3
    image: libming-4.7-swftophp-201711728-base:latest
    command: bash -c "bash script.sh && sleep infinity"
    working_dir: /workspace
    cpuset: "7"
    volumes:
      - libming-4.7_swftophp_2017-11728-afl-origin-3:/workspace/out

  afl-origin-4:
    container_name: libming-4.7_swftophp_2017-11728-afl-origin-4
    image: libming-4.7-swftophp-201711728-base:latest
    command: bash -c "bash script.sh && sleep infinity"
    working_dir: /workspace
    cpuset: "8"
    volumes:
      - libming-4.7_swftophp_2017-11728-afl-origin-4:/workspace/out

  afl-origin-5:
    container_name: libming-4.7_swftophp_2017-11728-afl-origin-5
    image: libming-4.7-swftophp-201711728-base:latest
    command: bash -c "bash script.sh && sleep infinity"
    working_dir: /workspace
    cpuset: "9"
    volumes:
      - libming-4.7_swftophp_2017-11728-afl-origin-5:/workspace/out

volumes:
  libming-4.7_swftophp_2017-11728-afl-origin-1:
  libming-4.7_swftophp_2017-11728-afl-origin-2:
  libming-4.7_swftophp_2017-11728-afl-origin-3:
  libming-4.7_swftophp_2017-11728-afl-origin-4:
  libming-4.7_swftophp_2017-11728-afl-origin-5:
