services:
  afl:
    container_name: libtiff-afl-test-baseline
    build: .
    command: /bin/bash -c "./run_all.sh && sleep infinity"
    working_dir: /workspace
    volumes:
      - libtiff-afl-out:/workspace/out
volumes:
  libtiff-afl-out:
