services:
  afl:
    container_name: php-afl-test-baseline
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - php-afl-out:/workspace/out
volumes:
  php-afl-out:
