FROM aflplusplus/aflplusplus:stable

RUN apt-get update && apt-get install -y \
    make cmake pkg-config wget curl git tmux libxml2-dev bison flex libsqlite3-dev unzip

WORKDIR /src

RUN git clone https://github.com/php/php-src.git && \
    cd php-src && \
    git checkout php-8.2.9

WORKDIR /src/php-src
RUN ./buildconf --force && \
    CC=afl-clang-lto CXX=afl-clang-lto++ ./configure \
    --enable-embed=static \
    --disable-all \
    --enable-cli \
    --without-iconv \
    --without-pear && \
    make -j$(nproc)

COPY harness.c .

RUN afl-clang-lto -O3 harness.c -o target_normal \
    -I/src/php-src \
    -I/src/php-src/main \
    -I/src/php-src/Zend \
    -I/src/php-src/TSRM \
    /src/php-src/libs/libphp.a \
    /usr/local/lib/afl/libAFLDriver.a \
    -lxml2 -lsqlite3 -ldl -lpthread -lm -lresolv

RUN mkdir -p /workspace
RUN cp target_normal /workspace/target_normal

RUN mkdir -p /workspace/in
RUN echo "<?php echo 'hello'; ?>" > /workspace/in/seed.php

WORKDIR /workspace
COPY run_all.sh /workspace/
RUN chmod +x run_all.sh
