services:
  afl:
    container_name: libxml2-afl-test-baseline
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - libxml2-afl-out:/workspace/out
volumes:
  libxml2-afl-out:
