services:
  afl:
    container_name: cjson-afl-test-baseline
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - cjson-afl-out:/workspace/out
volumes:
  cjson-afl-out: