FROM aflplusplus/aflplusplus:stable

RUN apt-get update && apt-get install -y \
    make cmake pkg-config wget curl git tmux perl

WORKDIR /src

RUN git clone https://github.com/openssl/openssl.git && \
    cd openssl && \
    git checkout openssl-3.1.2

WORKDIR /src/openssl
RUN ./config no-shared no-tests && \
    CC=afl-clang-lto make -j$(nproc)

COPY harness.c .

RUN afl-clang-lto -O3 harness.c -o target_normal \
    -I/src/openssl/include \
    /src/openssl/libssl.a \
    /src/openssl/libcrypto.a \
    /usr/local/lib/afl/libAFLDriver.a \
    -ldl -lpthread -lm

RUN mkdir -p /workspace
RUN cp target_normal /workspace/target_normal

RUN mkdir -p /workspace/in
RUN echo "dummy" > /workspace/in/seed

WORKDIR /workspace
COPY run_all.sh /workspace/
RUN chmod +x run_all.sh
