FROM my-aflplusplus:latest

RUN apt-get update && apt-get install -y \
    make cmake pkg-config wget curl git

WORKDIR /src

RUN git clone https://github.com/DaveGamble/cJSON.git && \
    cd cJSON && \
    git checkout v1.3.0

# add SOURCE_CODE_PATH environment variable for python scripts to locate the source code
ENV SOURCE_CODE_PATH=/src/cJSON
ENV AFL_OUT_DIR=/workspace/out

WORKDIR /src/cJSON
RUN mkdir -p build_ql && cd build_ql && \
    CC=clang CXX=clang++ cmake \
    -DENABLE_CJSON_TEST=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DENABLE_CJSON_UTILS=On \
    ..
RUN echo '#!/bin/bash\n\
make clean\n\
make -j$(nproc)' > /src/build_cjson.sh && chmod +x /src/build_cjson.sh

RUN codeql database create /src/codeqldb --language=cpp --command="/src/build_cjson.sh"

# ================= build cJSON with AFL instrumentation =================
RUN mkdir -p build && cd build && \
    CC=afl-clang-lto CXX=afl-clang-lto++ cmake \
    -DENABLE_CJSON_TEST=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DENABLE_CJSON_UTILS=On \
    .. && \
    make -j$(nproc)

RUN rm -f cfg_edges.txt

RUN codeql pack download codeql/cpp-queries
# extract possible targets from CodeQL analysis results
RUN codeql database analyze /src/codeqldb \
    codeql/cpp-queries:codeql-suites/cpp-security-and-quality.qls \
    --format=csv \
    --output=security_results.csv
RUN python3 /workspace/extract_targets.py

COPY harness.c .

RUN afl-clang-lto -O3 harness.c -o target_normal \
    -I/src/cJSON \
    /src/cJSON/build/libcjson.a \
    /src/cJSON/build/libcjson_utils.a \
    /usr/local/lib/afl/libAFLDriver.a \
    -ldl -lpthread -lm
RUN cp target_normal /workspace/target_normal
RUN cp *.txt /workspace || true

RUN mkdir -p /workspace/in
# Seed with some JSON files if available
RUN find /src/cJSON/tests/inputs -type f -exec cp {} /workspace/in/ \; || true

WORKDIR /workspace
COPY *.sh /workspace/
